### ISSUE TITLE
More website problems

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#384] opened 2018-07-20 19:06 UTC
I just clicked on ‘your account’ and got a server error. 

The librarian at Hereford said she can’t create an account. I tried registering and got this message...
<img width="379" alt="screen shot 2018-07-20 at 20 05 50" src="https://user-images.githubusercontent.com/10816169/43020582-6591ccf4-8c58-11e8-8626-5b880b8f20d6.png">

**Comment by ahankinson** [comment] 2018-07-20 19:09
I just tried and it worked, but I note that the checkbox for agreeing to the terms isn't showing in chrome...

**Comment by juliacmcf** [comment] 2018-07-20 19:16
the checkbox was showing in my chrome, and I checked it, but it still gave me that error.

**Comment by ahankinson** [comment] 2018-07-20 19:18
Can you reproduce it, and then send me the URL that it's trying to load (and failing)? When you get to the point where it gives you the error, copy and paste the address here.

**Comment by juliacmcf** [comment] 2018-07-21 07:36
weird that it worked. I’ll ask the Hereford lady to have another try and send the info if it fails.

**Comment by ahankinson** [comment] 2019-01-30 22:12
Seems to be fixed now? Closing for now.

**Closed by ahankinson** 2019-01-30 22:12 UTC
