### ISSUE TITLE
Deleting problem report from inside the report results in error

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#212] opened 2017-06-10 09:57 UTC
Hit delete inside problem report
Hit Yes I'm sure on next dialog
Then got error report attached. Probably did delete the report.
Deleting from the list was OK (David Wyatt had submitted 4 duplicate reports).

![screen shot 2017-06-10 at 10 54 39](https://user-images.githubusercontent.com/10816169/27001856-612454f6-4dcb-11e7-8ced-c97350197d56.png)

**Comment by ahankinson** [comment] 2017-06-10 12:17
Hm. I just tried this and couldn't reproduce. It seems it was trying to delete a page that was already deleted. 

We can keep an eye on this, but I'm going to close this issue for now.

**Closed by ahankinson** 2017-06-10 12:17 UTC
Labels: Component: User Interface, Priority: Low
