### ISSUE TITLE
Browse sources

### ISSUE THREAD

**Issue by ahankinson** [diamm/diamm#20] opened 2016-04-26 13:15 UTC
From an e-mail:

"In the new form of the website would it be helpful to be able to select country by alphabet letter at the top (as when one is searching journals on Jstor) rather than having to scroll through the whole lot?"

**Comment by ahankinson** [comment] 2016-05-14 23:28
We're going to focus on getting the search system working for the first public beta, and then look at methods of browsing sources.

**Comment by belljustin** [comment] 2016-07-06 19:23
closed as a duplicate of #96

**Closed by belljustin** 2016-07-06 19:23 UTC
Labels: Component: User Interface, Status: New, Type: Feature Request
